### ISSUE TITLE
Sound Settings Tab was empty when opened

### ISSUE THREAD

**Issue by hamzamaqsood877** [BurgerZ/MiBudsM8#10]
I've connected Redmi Buds 3 Pro. I also updated firmware to latest patched version. And everything is working fine EXCEPT sound settings.. There's nothing inside tjis option as shown in screenshot below.
![Screenshot_20230629-210558_Mi Buds M8.png](https://github.com/BurgerZ/MiBudsM8/assets/73820858/1b575e8c-0648-4fe3-807d-8c579945544d)

**Comment by ikerinagy** [comment]
I have the same issue, have you found a solution for it?

**Comment by BurgerZ** [comment]
Redmi Buds 3 Pro have nothing to configure, so the settings page is empty. Sound settings appear for some devices (for example Xiaomi Buds 3T). Another thing - the phone also should support spatial audio/virtual sound feature, otherwise those options are hidden/disabled.
