### ISSUE TITLE
Airbuds mode change buttons highlight on second press, while it works in single press

### ISSUE THREAD

**Issue by hamzamaqsood877** [BurgerZ/MiBudsM8#11]
I've appended the video of the issue where I had to press twice on an option to make it highlighted
https://github.com/BurgerZ/MiBudsM8/assets/73820858/2215f70c-86ee-4279-ac02-ff3de15da8a5

**Comment by BurgerZ** [comment]
The buttons highlight appears with some delay. Try to wait some time before clicking the button again.

**Comment by BurgerZ** [comment]
Should be fixed with v1.11.0
