### ISSUE TITLE
REDMI BUDS 4 PRO CN

### ISSUE THREAD

**Issue by Itzmepotato** [BurgerZ/MiBudsM8#15]
Issue with finding the 2.0.2.3 file for redmi buds 4 pro CN
Any ideas ?  
For CN-GLOBAL

**Comment by BurgerZ** [comment]
Firmwares 2.x.x.x are for GLOBAL versions of Redmi Buds 4 Pro (at the moment). So no way to "find" this version as an update for CN version of the earbuds.
