### ISSUE TITLE
Redmi Buds Pro 5 support?

### ISSUE THREAD

**Issue by devlincashman** [BurgerZ/MiBudsM8#16]
With these now being availably are there plans to support it? Would be greatly appreciated!

**Comment by BurgerZ** [comment]
Yes, currently I'm working on adding the following models to support list:
- Redmi Buds 4 哈利·波特版 (Harry Potter edition)
- Xiaomi Buds 3 Star Wars
- Redmi Buds 5
- Redmi Buds 5 AAPE
- Redmi Buds 5 Pro 
- Redmi Buds 5 Pro Gaming

**Comment by devlincashman** [comment]
Thank you so much! I love your app it has improved my life 😄.
