### ISSUE TITLE
Feature Request: Add support for Xiaomi Redmi Buds 4 Lite

### ISSUE THREAD

**Issue by FaserF** [BurgerZ/MiBudsM8#4]
https://www.mi.com/de/product/redmi-buds-4-lite/
Product is now released global and has been released about 4 weeks ago in china.

**Comment by snoopyxz** [comment]
I need it too I can't connect my Redmi buds 4 lite.

**Comment by BurgerZ** [comment]
Lite versions of earbuds will not be supported due to no possibility to change any of device settings.
