### ISSUE TITLE
Проблема с всплывающим окном, приложение не запускается при подключении наушников 

### ISSUE THREAD

**Issue by omsound** [BurgerZ/MiBudsM8#5]
1. Встроенное всплывающее окно смартфона конфликтует с всплывающим окном приложения насколько я понял, смотрите видео:

https://user-images.githubusercontent.com/127338178/229642889-df942a28-2835-47e7-a8ca-d44722e20d7f.mp4

(видео замедленно)

При отключении в настройках блютуз "Быстрого сопряжения с совместимыми устройствами" встроенное всплывающее окно не показывается, но всплывающего окна приложения так же нет.
Так же несколько раз было так что уведомление от приложения появлялось при закрытии крышки чехла наушников.

2. Приложение в какой то момент "засыпает" и при подключении наушников ничего не происходит, ни всплывающего окна ни виджета в шторке уведомлений.

Автозапуск включен, оптимизация - без ограничений, даже закрепил в оперативной памяти, но это не помогает, приложение какое то время запускается само но потом опять "засыпает"

![IMG_20230404_015401](https://user-images.githubusercontent.com/127338178/229643957-3e7fa055-7537-4871-ae2f-5f380a13decb.jpg)

Телефон Xiaomi 12T PRO, MIUI 14, наушники xiaomi buds 3

Так же в приложении есть функция улучшения звука (не помню точного названия сейчас), при включении ничего не происходит, звук не меняется)

**Comment by omsound** [comment]
Очень печально что вы забросили приложение! А могли бы это монетизировать, так как сяоми плевать на своих пользователей и родное приложение просто шлак! Но вам похоже тоже. Отправлял вам донат но жалею об этом

**Comment by BurgerZ** [comment]
Монетизировать увы ничего не получилось (рекламу встраивать в приложение я не планировал).

**Comment by omsound** [comment]
Андрей здравствуйте! Ждать от вас доработки приложения?14:56, 20 января 2024 г., Andrei Zhukouski ***@***.***>:
Монетизировать увы ничего не получилось (рекламу встраивать в приложение я не планировал).

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Best regards
